services:

  wryco_adminer_test:
    build:
      context: ./
      dockerfile: ./docker/test/adminer/Dockerfile
    container_name: wryco_adminer_test
    depends_on:
      - wryco_mssql_test
    env_file:
      - ./docker/test/adminer/.env.local
    image: wryco_adminer_test
    ports:
      - 8000:8080
    networks:
      - wryco_test

  wryco_aspnet_test:
    build:
      context: ./
      dockerfile: ./docker/test/aspnet/Dockerfile
    container_name: wryco_aspnet_test
    depends_on:
      - wryco_mssql_test
    env_file:
      - ./docker/test/aspnet/.env.local
    image: wryco_aspnet_test
    volumes:
      - ./src/backend:/wryco
    networks:
      - wryco_test

  wryco_mssql_test:
    build:
      context: ./
      dockerfile: ./docker/test/mssql/Dockerfile
    container_name: wryco_mssql_test
    env_file:
      - ./docker/test/mssql/.env.local
    image: wryco_mssql_test
    volumes:
      - ./docker/test/mssql/data:/var/opt/mssql/data
    networks:
      - wryco_test

  wryco_nginx_test:
    container_name: wryco_nginx_test
    build:
      context: ./
      dockerfile: docker/test/nginx/Dockerfile
    depends_on:
      - wryco_aspnet_test
    image: wryco_nginx_test
    ports:
      - 443:443
    volumes:
      - ./docker/test/nginx/logs:/var/log/nginx
    networks:
      - wryco_test

  wryco_vue_test:
    build:
      context: ./
      dockerfile: ./docker/test/vue/Dockerfile
    container_name: wryco_vue_test
    depends_on:
      - wryco_aspnet_test
    env_file:
      - ./docker/test/vue/.env.local
    image: wryco_vue_test
    volumes:
      - ./src/frontend:/wryco
    networks:
      - wryco_test

networks:

  wryco_test:
    name: wryco_test
    driver: bridge
